### PR TITLE
[nrf noup] Adapt ieee802154_nrf5 driver to TFM

### PR DESCRIPTION
**Pull request by Damian-Nordic**
* When CONFIG_BUILD_WITH_TFM=y, use tfm_platform_mem_read()
    to read EUI64 from the non-secure zone.
* Include secure_services.h header only if SPM=y.

Signed-off-by: Damian Krolik <damian.krolik@nordicsemi.no>

### CODE REVIEW

**Comment by ioannisg** [comment]
@Damian-Nordic SPM has no upstream support so the "toup" source needs to be "noup", I suppose.

**Comment by Damian-Nordic** [comment]
> @Damian-Nordic SPM has no upstream support so the "toup" source needs to be "noup", I suppose.

I realized that https://github.com/nrfconnect/sdk-nrf/pull/4106/files has already been added, so I changed the PR to provide a proper TF-M based implementation.

**Review by hakonfam — APPROVED** [review]
Use of `tfm_platform_mem_read` looks good.

**Comment by frkv** [comment]
@tejlmand: This suddenly has the previous version using prj.conf as "changed files" (and not the overlay-tfm.conf) Something happened during force-push?

**Comment by Damian-Nordic** [comment]
> @tejlmand: This suddenly has the previous version using prj.conf as "changed files" (and not the overlay-tfm.conf) Something happened during force-push?

Looks like the base has changed. I'll rebase again.

**Review by frkv — COMMENTED** [review]
Read service look fine, btw

**Pull request closed without merging**
